// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace firstApplication.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20211119172725_MigrationExample")]
    partial class MigrationExample
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("firstApplication.Models.Leaders", b =>
                {
                    b.Property<int>("LeadersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeadersID");

                    b.ToTable("Leaders");
                });

            modelBuilder.Entity("firstApplication.Models.Projects", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescriptionProject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FinishProject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LeadersID")
                        .HasColumnType("int");

                    b.Property<string>("StartProject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectID");

                    b.HasIndex("LeadersID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("firstApplication.Models.Projects", b =>
                {
                    b.HasOne("firstApplication.Models.Leaders", "Leader")
                        .WithMany()
                        .HasForeignKey("LeadersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leader");
                });
#pragma warning restore 612, 618
        }
    }
}
